### ISSUE TITLE
api is not support tensorflow version 2.2+

### ISSUE THREAD

**Issue by gavinz8** [serengil/deepface#143]
api.py not support tensorflow version 2.2.0+, when i run it, report error function get_default_graph not found, and it's can't load some models, report ValueError: rate must be a scalar tensor or a float in the range [0, 1)
![image](https://user-images.githubusercontent.com/3375755/101460505-a4df0180-3974-11eb-8d4c-c35e35e61d5c.png)

**Comment by serengil** [comment]
this is an environmental issue. unit tests were run in tf 1.9.0. you might downgrade your tf version to handle this issue.

**Comment by KiLJ4EdeN** [comment]
This could easily be handled with "import tf.compat.v1 as tf", ofc needs to be applied to module level.

**Comment by serengil** [comment]
@KiLJ4EdeN you mean this import should be done in deepface or out of deepface?

**Comment by KiLJ4EdeN** [comment]
> @KiLJ4EdeN you mean this import should be done in deepface or out of deepface?

Sadly needs to be done for the whole module where tf 1.x stuff are imported, Might be worth trying on a separate branch though.

**Comment by serengil** [comment]
it seems that downgrade is easier :)

**Comment by gavinz8** [comment]
As your told, I downgrade my version as 1.9.0, but the other dependencies must dependent tensorflow version 2.2.0+ too, tha't a bad circle dependency, how i do?
![image](https://user-images.githubusercontent.com/3375755/101567064-1bc6d980-3a0b-11eb-9a89-c4d62f2821be.png)

**Comment by serengil** [comment]
could you downgrade other dependencies as mentioned. if it says keras>=2.2.0 then, downgrade keras to 2.2.0 (pip install keras==2.2.0).

**Comment by serengil** [comment]
I fixed this issue. deepface will be compatible with tf 2. I plan to release it tomorrow.

**Comment by serengil** [comment]
this is solved in 0.0.46 release right now.

**Comment by shrhawk-entertainer** [comment]
@serengil still the same issue

`obj = DeepFace.analyze(img_path = "test_image.jpg", actions = ['age', 'gender', 'race', 'emotion'])`

it giving the following error on **TensorFlow version 2.3.1**
```
graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
```

**Comment by serengil** [comment]
@shrhawk-entertainer you are using the latest version of deepface - 0.0.49? Because, as you can see [here](https://github.com/serengil/deepface/blob/master/api/api.py) - 86th line, graph = tf.get_default_graph() code is not running for tensorflow.

**Comment by shrhawk-entertainer** [comment]
@serengil yes I am using version **0.0.49** and the code you mentioned above is for API but I am invoking the deepface from the python shell
```
from deepface import DeepFace
obj = DeepFace.analyze(img_path = "test_image.jpg", actions = ['age', 'gender', 'race', 'emotion'])
```

the traceback error is 

```
envname/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 74, in get_uid
  graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
```

**Comment by serengil** [comment]
could you share the all log here. I could not understand where this error come from. Which line of the deepface.py.

**Comment by shrhawk-entertainer** [comment]
here's the complete log

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shrhawk/envname/lib/python3.7/site-packages/deepface/DeepFace.py", line 309, in analyze
    functions.initialize_detector(detector_backend = detector_backend)
  File "/Users/shrhawk/envname/lib/python3.7/site-packages/deepface/commons/functions.py", line 136, in initialize_detector
    face_detector = MTCNN()
  File "/Users/shrhawk/envname/lib/python3.7/site-packages/mtcnn/mtcnn.py", line 88, in __init__
    self._pnet, self._rnet, self._onet = NetworkFactory().build_P_R_O_nets_from_file(weights_file)
  File "/Users/shrhawk/envname/lib/python3.7/site-packages/mtcnn/network/factory.py", line 123, in build_P_R_O_nets_from_file
    p_net = self.build_pnet()
  File "/Users/shrhawk/envname/lib/python3.7/site-packages/mtcnn/network/factory.py", line 38, in build_pnet
    p_inp = Input(input_shape)
  File "/Users/shrhawk/envname/lib/python3.7/site-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/Users/shrhawk/envname/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/shrhawk/envname/lib/python3.7/site-packages/keras/engine/input_layer.py", line 39, in __init__
    name = prefix + '_' + str(K.get_uid(prefix))
  File "/Users/shrhawk/envname/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 74, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
```

**Comment by serengil** [comment]
Oke I think I understood. MTCNN requires Keras dependency. I am using tensorflow 2.3.1 and keras 2.4.3.

You can either install keras with the command "pip install keras" 

Or you can change the face detector backend as shown below

`obj = DeepFace.analyze(img_path = "test_image.jpg", actions = ['age', 'gender', 'race', 'emotion'], detector_backend = 'opencv')`

**Comment by shrhawk-entertainer** [comment]
@serengil Keras is already installed with version **2.2.4**

**Comment by serengil** [comment]
as I mentioned, you cannot import MTCNN that's the problem. I can import it with tf 2.3.1 and keras 2.4.3. Upgrading keras to 2.4.3 might solve this but you should try.

You might open an issue to mtcnn repo directly [here](https://github.com/ipazc/mtcnn). I recommend you to use opencv backend as a workaround.
