### ISSUE TITLE
import error: illegal hardware instruction

### ISSUE THREAD

**Issue by sun-peach** [serengil/deepface#591]
Hi, I am running deepface on my Mac (system report listed below).
```Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	8419.41.10
  OS Loader Version:	7459.141.1
  Serial Number (system):	FVFGD1ZHQ05Q
  Hardware UUID:	C400510A-03B1-52C1-AF5E-F1D87F9FEED1
  Provisioning UDID:	00008103-000E30301A3B001E
  Activation Lock Status:	Disabled
```
I install deepface in my conda environment (python==3.8.13). I pip installed it and the installation was successful without any error (in fact, deepface is the first library I installed after I create this environment).

I run `from deepface import DeepFace` following the README. However, the python pops a piece of error `[1]    22199 illegal hardware instruction  python` and exit. I did not know why this happend. Anyone help?

Thank you in advance.

**Comment by sun-peach** [comment]
FYI, I uninstalled it and use conda to install it again. It works. Not sure why pip install does not work. BTW, I find the error step is `from deepface.basemodels import VGGFace, OpenFace, Facenet, Facenet512, FbDeepFace, DeepID, DlibWrapper, ArcFace, Boosting, SFaceWrapper` in DeepFace.py

**Comment by serengil** [comment]
oh happy to hear it is resolved

**Comment by sun-peach** [comment]
@serengil Sefik, in fact it is not solved (I am going to re-open it). When I use conda, it works perfect; but if I use pip, it still does not work.
